### ISSUE TITLE
[FEATURE] TYPO3 13 Support?

### ISSUE THREAD

**Issue by BokuNoMaxi** [web-vision/deepltranslate-core#369]
When can we estimate to use this extension for TYPO3 13 projects? I could help out if you have missing resources ;)

**Comment by borishinzer** [comment]
Hi, we aim to have a v13 ready by the end of this year.

**Comment by sbuerk** [comment]
@BokuNoMaxi We released today the new 5.0.0 version with TYPO3 v12 and v13 support: https://github.com/web-vision/deepltranslate-core/releases

The glossary management and handling has been exractd into a adedicated public addon extension,
see https://github.com/web-vision/deepltranslate-glossary/releases.

Going to close this issue now as resolved.
