### ISSUE TITLE
[BUG] Adding Access control for backend users crashes non-configured systems

### ISSUE THREAD

**Issue by schugabe** [web-vision/deepltranslate-core#379]
**Describe the task**

The release 4.4.0 contains this change https://github.com/web-vision/deepltranslate-core/pull/361 and I think this is a breaking change since the extensions did stop working for users and I had to modify the group permissions.

**Expected behavior**
Increase major version to indicate breaking change and document this breaking change in the changelog file.

**Additional context**
I don't know if you use semantic versioning but imho it would be a good idea to use it for future releases.

**Comment by schugabe** [comment]
Before that release the same users used deepl without any issue (version 4.3.1)

With the 4.4.0 release all deepl options are invisible for normal users (admin user still sees the translate with deepl options). 

I added the permission for "Allowed Translate" in the custom_options section for the user group and the translate buttons did show up again. 

Let me know if you need more information.

**Comment by calien666** [comment]
I guess, this should be enough. I'll take a look asap and keep you informed. This shouldn't happen.

**Comment by calien666** [comment]
Release 4.4.1 with fixing this behaviour incoming. Thanks for reporting
